In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df= pd.read_csv('/content/ecommerce_sales.csv')

In [5]:
df.head()

,OrderID,CustomerID,Product,Category,Quantity,Price,Discount,Region,Gender,Age,OrderDate
0,1001,C001,Laptop,Electronics,1,55000,5000,North,Male,25,15-01-2024
1,1002,C002,Phone,Electronics,2,25000,2000,South,Female,30,16-01-2024
2,1003,C003,Shoes,Fashion,3,2000,200,West,Male,22,17-01-2024
3,1004,C004,T-Shirt,Fashion,5,800,50,East,Female,28,18-01-2024
4,1005,C005,Watch,Accessories,2,5000,500,North,Male,35,19-01-2024

In [6]:
p = np.array(df['Quantity'])

In [7]:
p

array([1, 2, 3, 5, 2, 4, 1, 1, 2, 3, 1, 2, 4, 2, 3])

In [8]:
p.mean()

np.float64(2.4)

In [10]:
p.max()

np.int64(5)

In [11]:
p.min()

np.int64(1)

In [12]:
df['Price'].mean()

np.float64(14833.333333333334)

In [13]:
df['Price'].std()

20202.14510062401

In [14]:
revenue = df['Quantity'] * df['Price']

In [15]:
revenue

0     55000
1     50000
2      6000
3      4000
4     10000
5      6000
6      2500
7     30000
8      4000
9     15000
10    60000
11    56000
12     3600
13     6000
14     5400
dtype: int64

In [22]:
#add revenue column to the dataset
df['Revenue'] = revenue
df

,OrderID,CustomerID,Product,Category,Quantity,Price,Discount,Region,Gender,Age,OrderDate,Revenue
0,1001,C001,Laptop,Electronics,1,55000,5000,North,Male,25,15-01-2024,55000
1,1002,C002,Phone,Electronics,2,25000,2000,South,Female,30,16-01-2024,50000
2,1003,C003,Shoes,Fashion,3,2000,200,West,Male,22,17-01-2024,6000
3,1004,C004,T-Shirt,Fashion,5,800,50,East,Female,28,18-01-2024,4000
4,1005,C005,Watch,Accessories,2,5000,500,North,Male,35,19-01-2024,10000
5,1006,C006,Headphones,Electronics,4,1500,100,South,Female,24,20-01-2024,6000
6,1007,C007,Bag,Fashion,1,2500,200,West,Male,27,21-01-2024,2500
7,1008,C008,Tablet,Electronics,1,30000,3000,East,Female,32,22-01-2024,30000
8,1009,C009,Shoes,Fashion,2,2000,100,North,Male,21,23-01-2024,4000
9,1010,C010,Watch,Accessories,3,5000,400,South,Female,29,24-01-2024,15000
10,1011,C011,Laptop,Electronics,1,60000,5000,West,Male,40,25-01-2024,60000
11,1012,C012,Phone,Electronics,2,28000,2500,East,Female,26,26-01-2024,56000
12,1013,C013,T-Shirt,Fashion,4,900,100,North,Male,23,27-01-2024,3600
13,1014,C014,Bag,Fashion,2,3000,250,South,Female,31,28-01-2024,6000
14,1015,C015,Headphones,Electronics,3,1800,150,West,Male,34,29-01-2024,5400

In [21]:
#top 3 revenue
df.sort_values(by='Revenue', ascending=False).head(3)

,OrderID,CustomerID,Product,Category,Quantity,Price,Discount,Region,Gender,Age,OrderDate,Revenue
10,1011,C011,Laptop,Electronics,1,60000,5000,West,Male,40,25-01-2024,60000
11,1012,C012,Phone,Electronics,2,28000,2500,East,Female,26,26-01-2024,56000
0,1001,C001,Laptop,Electronics,1,55000,5000,North,Male,25,15-01-2024,55000

In [23]:
df.head(5)

,OrderID,CustomerID,Product,Category,Quantity,Price,Discount,Region,Gender,Age,OrderDate,Revenue
0,1001,C001,Laptop,Electronics,1,55000,5000,North,Male,25,15-01-2024,55000
1,1002,C002,Phone,Electronics,2,25000,2000,South,Female,30,16-01-2024,50000
2,1003,C003,Shoes,Fashion,3,2000,200,West,Male,22,17-01-2024,6000
3,1004,C004,T-Shirt,Fashion,5,800,50,East,Female,28,18-01-2024,4000
4,1005,C005,Watch,Accessories,2,5000,500,North,Male,35,19-01-2024,10000

In [24]:
df.tail(5)

,OrderID,CustomerID,Product,Category,Quantity,Price,Discount,Region,Gender,Age,OrderDate,Revenue
10,1011,C011,Laptop,Electronics,1,60000,5000,West,Male,40,25-01-2024,60000
11,1012,C012,Phone,Electronics,2,28000,2500,East,Female,26,26-01-2024,56000
12,1013,C013,T-Shirt,Fashion,4,900,100,North,Male,23,27-01-2024,3600
13,1014,C014,Bag,Fashion,2,3000,250,South,Female,31,28-01-2024,6000
14,1015,C015,Headphones,Electronics,3,1800,150,West,Male,34,29-01-2024,5400

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     15 non-null     int64
 1   CustomerID  15 non-null     object
 2   Product     15 non-null     object
 3   Category    15 non-null     object
 4   Quantity    15 non-null     int64
 5   Price       15 non-null     int64
 6   Discount    15 non-null     int64
 7   Region      15 non-null     object
 8   Gender      15 non-null     object
 9   Age         15 non-null     int64
 10  OrderDate   15 non-null     object
 11  Revenue     15 non-null     int64
dtypes: int64(6), object(6)
memory usage: 1.5+ KB

In [29]:
df.isnull().sum()

OrderID       0
CustomerID    0
Product       0
Category      0
Quantity      0
Price         0
Discount      0
Region        0
Gender        0
Age           0
OrderDate     0
Revenue       0
dtype: int64

In [31]:
#revenue = (quantity*price) - discount
revenue = df['Quantity']* df['Price'] - df['Discount']

In [32]:
revenue

0     50000
1     48000
2      5800
3      3950
4      9500
5      5900
6      2300
7     27000
8      3900
9     14600
10    55000
11    53500
12     3500
13     5750
14     5250
dtype: int64

In [33]:
revenue.sum()

np.int64(293950)

In [34]:
revenue.mean()

np.float64(19596.666666666668)

In [35]:
revenue.max()

55000